version: "3"

services:
  app:
    image: rust:1.40-alpine
    volumes:
      - .:${PWD}
      - cargo-data:/usr/local/cargo
      - rustup-data:/usr/local/rustup
    working_dir: ${PWD}

volumes:
  cargo-data:
  rustup-data:
